server:
  port: 8081

spring:
  application:
    name: kiranaos-auth-service

  datasource:
    url: jdbc:postgresql://db.shtsascslrhehnisitvl.supabase.co:5432/postgres?sslmode=require
    username: postgres
    password: lbTEnRvbS2teSk3R
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: your-256-bit-secret-key-here-replace-in-prod  # min 32 chars
  access-token-expiry-ms: 900000        # 15 minutes
  refresh-token-expiry-ms: 604800000    # 7 days
